export const AUTH_FEATURE_CONFIG = Symbol('AUTH_FEATURE_CONFIG');
export const USERS_FEATURE_CONFIG = Symbol('USERS_FEATURE_CONFIG');
export const ORGS_FEATURE_CONFIG = Symbol('ORGS_FEATURE_CONFIG');
export const MEMBERS_FEATURE_CONFIG = Symbol('MEMBERS_FEATURE_CONFIG');
export const INVITES_FEATURE_CONFIG = Symbol('INVITES_FEATURE_CONFIG');
export const PROFILES_FEATURE_CONFIG = Symbol('PROFILES_FEATURE_CONFIG');
export const ACCOUNT_FEATURE_CONFIG = Symbol('ACCOUNT_FEATURE_CONFIG');
